version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "@Admin2w6y1q1q"
      MYSQL_DATABASE: waiting_list_db
      MYSQL_USER: superuser
      MYSQL_PASSWORD: "@Admin2w6y1q1q"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p@Admin2w6y1q1q"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend_express_app:
    image: ${DOCKER_HUB_USERNAME}/backend_express_app:latest # Ganti ini!
    container_name: backend_express_app_container
    ports:
      - "3003:3003"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: superuser
      DB_PASSWORD: "@Admin2w6y1q1q"
      DB_NAME: waiting_list_db
      PORT: 3003
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: adminpassword
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "8080:80"
      - "4430:443"
    depends_on:
      - backend_express_app
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge