name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger pipeline saat ada push ke branch main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }} # Token akses Docker Hub Anda

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend # Lokasi Dockerfile Anda (relative ke root repo)
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend_express_app:latest
        platforms: linux/amd64 # Pastikan platform yang benar

  deploy:
    runs-on: ubuntu-latest # Atau server VPS Anda
    needs: build_and_push # Pastikan tahap build dan push selesai
    environment: production # Opsional: Lingkungan deployment

    steps:
    - name: Checkout code (optional, if you pull docker-compose.yml directly)
      uses: actions/checkout@v4

    - name: Login to Docker Hub (on deployment server)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Pull and run Docker Compose stack
      run: |
        # Navigasi ke direktori tempat docker-compose.yml Anda
        # Misalnya, jika Anda punya repo di /home/user/my-app
        cd /home/superuser/projectApp/waiting-list-crud-react-native-v2
        # Tarik image terbaru dan jalankan ulang stack
        docker-compose down # Hentikan kontainer lama jika ada
        docker-compose pull # Tarik image terbaru dari Docker Hub
        docker-compose up -d --remove-orphans # Jalankan kontainer baru